import type { NextPage } from "next";
import Head from "next/head";
import { Flex } from "@chakra-ui/react";
import Header from "../components/Header";
import Container from "../components/Container";

const Home: NextPage = () => {
  return (
    <Flex className="w-full flex flex-col h-screen">
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <Flex className="w-full h-full flex flex-col">
        <Header />
        <Container />
      </Flex>
    </Flex>
  );
};

export default Home;
